name: Build batt_design_override (Auto GKI Fetch)

on:
  workflow_dispatch:
    inputs:
      kernel_lines:
        description: '内核主线列表: 5.4,5.10,5.15,6.1 (空=全部)'
        required: false
        default: ''
      version:
        description: '模块版本号 (空=module.prop)'
        required: false
        default: ''
      release:
        description: '发布 Release (true/false)'
        required: false
        default: 'false'
      refresh_sources:
        description: '强制刷新 GKI 源码缓存 (true/false)'
        required: false
        default: 'false'
      custom_repo_url:
        description: '自定义内核源码仓库 (可选, 例如 https://github.com/xxx/kernel.git)'
        required: false
        default: ''
      custom_ref:
        description: '自定义仓库分支/标签 (与 custom_repo_url 搭配)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        kernel_line: ["5.4", "5.10", "5.15", "6.1"]
    env:
      MODULE_ID: batt-design-override
      MAGISK_DIR: packaging/magisk-batt-design-override
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      ARCH: arm64
      LLVM: 1
      LLVM_IAS: 1
      JOBS: 8
      LTO_JOBS: 8
    steps:
      - uses: actions/checkout@v4
      - name: 过滤所需内核
        id: filter
        run: |
          REQ='${{ github.event.inputs.kernel_lines }}'
          if [[ -z "$REQ" ]]; then B=1; else
            WANT=$(echo "$REQ" | tr ' ' ',' | sed 's/,,*/,/g' | sed 's/^,//;s/,$//')
            IFS=',' read -r -a ARR <<< "$WANT"; B=0; for k in "${ARR[@]}"; do [[ "$k" == "${{ matrix.kernel_line }}" ]] && B=1; done
          fi
          echo "build=$B" >> $GITHUB_OUTPUT
      - name: 跳过标记
        if: steps.filter.outputs.build != '1'
        run: echo "Skip ${{ matrix.kernel_line }}"
      - name: 安装依赖
        if: steps.filter.outputs.build == '1'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends cpio libelf-dev bc flex bison python3 rsync build-essential zip unzip file jq git lld clang llvm llvm-dev llvm-runtime
          echo "[i] Host clang:"; clang --version || true
          echo "[i] Host ld.lld path:"; command -v ld.lld || true
          # 某些 runner 镜像可能只有 /usr/lib/llvm-*/bin/ld.lld 未放入 PATH
          if ! command -v ld.lld >/dev/null 2>&1; then
            FOUND=$(command -v /usr/lib/llvm-*/bin/ld.lld 2>/dev/null | head -n1 || true)
            if [[ -n "$FOUND" ]]; then sudo ln -sf "$FOUND" /usr/local/bin/ld.lld; fi
          fi
          if ! command -v ld.lld >/dev/null 2>&1; then echo "::error ::仍未找到 ld.lld"; exit 2; fi
      - name: 分支候选 (准备)
        if: steps.filter.outputs.build == '1'
        id: branch_select
        run: |
          case "${{ matrix.kernel_line }}" in
            5.4)  CANDIDATES=(android11-5.4 android12-5.10 android-mainline); OUT=gki/out-5.4 ;;
            5.10) CANDIDATES=(android12-5.10 android13-5.10 android-mainline); OUT=gki/out-5.10 ;;
            5.15) CANDIDATES=(android13-5.15 android14-6.1 android-mainline); OUT=gki/out-5.15 ;;
            6.1)  CANDIDATES=(android14-6.1 android-mainline); OUT=gki/out-6.1 ;;
            *) echo '未知 kernel_line' >&2; exit 2;;
          esac
          mkdir -p gki "$OUT"
          echo "candidates=${CANDIDATES[*]}" >> $GITHUB_OUTPUT
          echo "out=$OUT" >> $GITHUB_OUTPUT
          echo "[i] 候选分支: ${CANDIDATES[*]}"
      - name: 选择并克隆分支
        if: steps.filter.outputs.build == '1'
        id: fetch_kernel
        run: |
          set -e
          CANDIDATES='${{ steps.branch_select.outputs.candidates }}'
          CUSTOM_URL='${{ github.event.inputs.custom_repo_url }}'
          CUSTOM_REF='${{ github.event.inputs.custom_ref }}'
          if [[ -n "$CUSTOM_URL" && -n "$CUSTOM_REF" ]]; then
            echo "[i] 使用自定义仓库: $CUSTOM_URL @ $CUSTOM_REF"
            git clone --depth=1 --branch "$CUSTOM_REF" "$CUSTOM_URL" gki/custom-src
            SELECTED="$CUSTOM_REF"; SRC_PATH="gki/custom-src"
          else
            SELECTED=""
            for cand in $CANDIDATES; do
              echo "[i] 尝试分支: $cand"
              if [[ -d gki/$cand && -f gki/$cand/Makefile ]]; then
                SELECTED="$cand"; SRC_PATH="gki/$cand"; break
              fi
              rm -rf gki/tmp-clone
              git clone --depth=1 --branch "$cand" https://android.googlesource.com/kernel/common gki/tmp-clone 2>/dev/null || continue
              mv gki/tmp-clone gki/$cand
              SELECTED="$cand"; SRC_PATH="gki/$cand"; break
            done
          fi
          if [[ -z "$SELECTED" ]]; then
            echo "::error ::未能匹配任何有效分支 ($CANDIDATES)，可提供 custom_repo_url+custom_ref"; exit 2
          fi
          echo "branch=$SELECTED" >> $GITHUB_OUTPUT
          echo "src=$SRC_PATH" >> $GITHUB_OUTPUT
          echo "out=${{ steps.branch_select.outputs.out }}" >> $GITHUB_OUTPUT
          echo "[i] 已选择: $SELECTED -> $SRC_PATH"
      - name: 强制刷新源码 (可选)
        if: steps.filter.outputs.build == '1' && github.event.inputs.refresh_sources == 'true'
        run: |
          SRC='${{ steps.fetch_kernel.outputs.src }}'
          BR='${{ steps.fetch_kernel.outputs.branch }}'
          if [[ "$SRC" == gki/custom-src ]]; then
            echo "[i] 自定义仓库不自动刷新"
          else
            echo "[i] 刷新 $BR"
            rm -rf "$SRC"
            git clone --depth=1 --branch "$BR" https://android.googlesource.com/kernel/common "$SRC"
          fi
      - name: 生成元数据 (日期+模块哈希)
        if: steps.filter.outputs.build == '1'
        id: meta
        run: |
          DATE_TAG=$(date +%Y%m%d)
          MOD_HASH=$( (sha256sum extra_modules/batt_design_override/*.c 2>/dev/null; sha256sum extra_modules/batt_design_override/Makefile) | sha256sum | cut -d' ' -f1 )
          echo "date=$DATE_TAG" >> $GITHUB_OUTPUT
          echo "mod_hash=$MOD_HASH" >> $GITHUB_OUTPUT
          echo "::notice title=ModuleHash::$MOD_HASH"
      - name: 缓存源码
        if: steps.filter.outputs.build == '1'
        uses: actions/cache@v4
        with:
          path: ${{ steps.fetch_kernel.outputs.src }}
          key: src-${{ steps.fetch_kernel.outputs.branch }}-${{ steps.meta.outputs.date }}
          restore-keys: |
            src-${{ steps.fetch_kernel.outputs.branch }}-
      - name: 缓存 out
        if: steps.filter.outputs.build == '1'
        uses: actions/cache@v4
        with:
          path: ${{ steps.fetch_kernel.outputs.out }}
          key: out-${{ steps.fetch_kernel.outputs.branch }}-${{ steps.meta.outputs.date }}-${{ steps.meta.outputs.mod_hash }}
          restore-keys: |
            out-${{ steps.fetch_kernel.outputs.branch }}-${{ steps.meta.outputs.date }}-
            out-${{ steps.fetch_kernel.outputs.branch }}-
      - name: 缓存 ccache
        if: steps.filter.outputs.build == '1'
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ccache-${{ steps.fetch_kernel.outputs.branch }}-${{ steps.meta.outputs.mod_hash }}
          restore-keys: |
            ccache-${{ steps.fetch_kernel.outputs.branch }}-
      - name: 构建模块
        if: steps.filter.outputs.build == '1'
        run: |
          set -e
          KERNEL_SRC='${{ steps.fetch_kernel.outputs.src }}'
          KERNEL_OUT='${{ steps.fetch_kernel.outputs.out }}'
          ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CLANG_TRIPLE=aarch64-linux-gnu-
          export LLVM=1 LLVM_IAS=1
          if ! command -v ld.lld >/dev/null 2>&1; then echo "::error ::缺少 ld.lld"; exit 2; fi
          if [[ ! -f "$KERNEL_OUT/.config" ]]; then
            if ! make -C "$KERNEL_SRC" O="$KERNEL_OUT" ARCH=$ARCH LLVM=1 LLVM_IAS=1 \
              CC=clang LD=ld.lld CLANG_TRIPLE=$CLANG_TRIPLE CROSS_COMPILE=$CROSS_COMPILE \
              LLVM_AR=llvm-ar LLVM_NM=llvm-nm LLVM_OBJCOPY=llvm-objcopy LLVM_OBJDUMP=llvm-objdump \
              READELF=llvm-readelf STRIP=llvm-strip gki_defconfig; then
              echo "::group::可用 *gki* defconfig 列表"; ls "$KERNEL_SRC"/arch/arm64/configs/*gki* 2>/dev/null || true; echo "::endgroup::";
              echo "::error ::gki_defconfig 失败 (branch='${{ steps.fetch_kernel.outputs.branch }}')"; exit 2; fi
          fi
          make -C "$KERNEL_SRC" O="$KERNEL_OUT" ARCH=$ARCH LLVM=1 LLVM_IAS=1 CC=clang LD=ld.lld olddefconfig || true
          if [[ ! -f "$KERNEL_OUT/Module.symvers" ]]; then
            echo "[i] 初始化 modules (生成符号)";
            make -C "$KERNEL_SRC" O="$KERNEL_OUT" ARCH=$ARCH LLVM=1 LLVM_IAS=1 CC=clang LD=ld.lld -j$(nproc) modules || true
          fi
          make -C "$KERNEL_SRC" O="$KERNEL_OUT" ARCH=$ARCH LLVM=1 LLVM_IAS=1 CC=clang LD=ld.lld \
            M=extra_modules/batt_design_override -j$(nproc) modules
          test -f extra_modules/batt_design_override/batt_design_override.ko
      - name: 解析版本号
        if: steps.filter.outputs.build == '1'
        id: ver
        run: |
          BASE_VER=$(grep -E '^version=' packaging/magisk-batt-design-override/module.prop | cut -d= -f2-)
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            VER='${{ github.event.inputs.version }}'
          else
            VER="$BASE_VER"
          fi
          echo VERSION=$VER >> $GITHUB_ENV
          echo "version=$VER" >> $GITHUB_OUTPUT
      - name: 打包 Magisk 模块
        if: steps.filter.outputs.build == '1'
        run: |
          mkdir -p dist
          ./packaging/build_magisk_zip.sh \
            --ko extra_modules/batt_design_override/batt_design_override.ko \
            --kernel-line ${{ matrix.kernel_line }} \
            --version $VERSION \
            --output dist
          ls -l dist
      - name: 上传构件
        if: steps.filter.outputs.build == '1'
        uses: actions/upload-artifact@v4
        with:
          name: batt-design-override-${{ matrix.kernel_line }}
          path: |
            extra_modules/batt_design_override/batt_design_override.ko
            dist/*.zip
          if-no-files-found: error

  release:
    needs: build
    if: >-
      (github.event_name == 'workflow_dispatch' && inputs.release == 'true')
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: collected
      - name: Generate notes
        run: |
          echo "Release battmod-$(date +%Y%m%d-%H%M%S)" > NOTES.md
          find collected -name '*.zip' -printf '* %f\n' >> NOTES.md || true
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: battmod-${{ github.run_number }}
          name: battmod-${{ github.run_number }}
          body_path: NOTES.md
          files: |
            collected/**/*.zip
            collected/**/batt_design_override.ko
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
