name: Manual Trigger Test

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: '测试输入'
        required: false
        default: 'hello'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: |
          echo "Manual trigger test successful!"
          echo "Input: ${{ github.event.inputs.test_input }}"
