name: Test Actions

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Test basic functionality
        run: |
          echo "Testing Actions functionality..."
          echo "Current directory: $(pwd)"
          echo "Files in repo:"
          ls -la
          echo "Workflow files:"
          ls -la .github/workflows/
          echo "Actions test completed successfully!"
